### ISSUE TITLE
(React Router) Routes work only once

### ISSUE THREAD

**Issue by zemd** [RickWong/react-isomorphic-starterkit#15] opened 2015-03-12 09:45 UTC
Hi!
I am new to react and trying to figure out with this project, and stucked with a problem when add new route it can be viewed only once.

so added files and new route https://gist.github.com/hunterman/1f46436face225b25425 and then I can transit to any page only once after page loaded, after that page is not rerendering, but only pushState works.

**Comment by RickWong** [comment] 2015-03-12 17:14
Maybe because you only have `name=...` but don't have `path=...` attributes on the `<Route>` declarations.

**Comment by zemd** [comment] 2015-03-12 18:42
@RickWong thank you for your answer, but as you can see here https://github.com/rackt/react-router/blob/master/examples/transitions/app.js there is no path also, and here https://github.com/rackt/react-router/blob/master/docs/api/components/Route.md here is saying that 

> The path used in the URL. If left undefined, the path will be defined by the name, and if there is no name, will default to /.

also, why does it work only once? after I open page in browser I can navigate to another page, but after I've navigated I can't make it again.

ps to be sure added paths to routes definition, and it works the same, so not solved the issue

**Comment by RickWong** [comment] 2015-03-12 22:23
Do you get any console errors (in browser or in your terminal)? I too find it strange that it works just once. What does `About.jsx` look like?

**Comment by zemd** [comment] 2015-03-13 09:33
@RickWong no errors, made video https://dl.dropboxusercontent.com/u/19321079/routes.mov

About.jsx is simplest component as it can be

``` js
import React from 'react';

const About = React.createClass({
    render() {
        return (
            <div className="container">
                Hello World
            </div>
        );
    }
});


export default About;
```

**Comment by RickWong** [comment] 2015-03-15 14:21
Can you log the value that is passed to `this.transitionTo(...)` each time you click?

**Comment by RickWong** [comment] 2015-03-16 22:02
Closing issue because the problem isn't likely to be caused by the starterkit.

**Closed as completed by RickWong** 2015-03-16 22:02 UTC
Labels: question
