### ISSUE TITLE
two copies of React on the page

### ISSUE THREAD

**Issue by monte-hayward** [RickWong/react-isomorphic-starterkit#77] opened 2015-10-13 17:00 UTC
Shortly after startup, **_this**_ error occurs. Additional log output for context.

`npm run watch

> react-isomorphic-starterkit@3.0.4 watch /work/watson/react-isomorphic-starterkit
> node ./node_modules/concurrently/src/main.js --kill-others "npm run watch-client" "npm run start"

[1] 
[1] > react-isomorphic-starterkit@3.0.4 start /work/watson/react-isomorphic-starterkit
[1] > NODE_PATH="./src" node ./babel.server

0] > node ./node_modules/webpack/bin/webpack.js --verbose --colors --display-error-details --config webpack.client-watch.js && node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --config webpack.client-watch.js
[0] 
[0] Hash: b6e2dee34fe966773396
[0] Version: webpack 1.12.2
[0] Time: 2088ms
[0]     Asset     Size  Chunks             Chunk Names
[0] client.js  1.28 MB       0  [emitted]  main
[0]    [0] multi main 52 bytes {0} [built]
[0]     + 356 hidden modules
[0] http://localhost:8080/
[0] webpack result is served from http://localhost:8080/dist/
[0] content is served from ./static
[1] ==> ✅  Server is listening
[1] ==> 🌎  Go to http://localhost:8000
[1] Warning: [history] Calling createLocation statically is deprecated; instead call the history.createLocation method - see docs/Location.md
[1] Hello server

**_[1] Warning: React can't find the root component node for data-reactid value `.1ephdw71gcg`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.**_ 

[1] Warning: React can't find the root component node for data-reactid value `.1ephdw71gcg.0:0.0`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.
[1] Hello server
[1] Warning: [history] Calling createLocation statically is deprecated; instead call the history.createLocation method - see docs/Location.md
[1] Hello server
[1] Warning: React can't find the root component node for data-reactid value `.sjuqfyqiv4`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.
[1] Warning: React can't find the root component node for data-reactid value `.sjuqfyqiv4.0:0.0`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.
[1] Hello server

[1] Warning: [history] Calling createLocation statically is deprecated; instead call the history.createLocation method - see docs/Location.md
[1] Hello server
[1] Warning: React can't find the root component node for data-reactid value `.1nb1515t0cg`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.
`

**Comment by ghost** [comment] 2015-10-26 21:39
+1

[Edit] My issues were actually coming from [react-dropzone-component](https://github.com/felixrieseberg/React-Dropzone-Component).  It seems that something was merged over the weekend which re-instantiates the React class per page.

**Comment by Jimtattersall** [comment] 2015-10-26 21:56
+1, i'm seeing. 

`Warning: React can't find the root component node for data-reactid value `.1zvqzr7nc3k.3.$=1$/package`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.`

The issue seems to be related to transmit, but only when fetching data for the page.

**Comment by shankie-codes** [comment] 2015-10-28 18:38
Same here

**Comment by tylermadison** [comment] 2015-11-02 01:48
+1 same here, pulled repo fresh install...node version v3.3.1

```
Warning: [history] Calling createLocation statically is deprecated; instead call the history.createLocation method - see docs/Location.md
[1] Hello server
[1] Warning: React can't find the root component node for data-reactid value `.gkf1g3mjnk`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.
[1] Warning: React can't find the root component node for data-reactid value `.gkf1g3mjnk.0:0.0`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.
[1] Hello server
```

**Comment by RickWong** [comment] 2015-11-03 23:32
It is actually Transmit. Will look into it further.

**Comment by RickWong** [comment] 2015-11-04 00:47
It's fixed in Transmit 3.0.8. Apparently it's caused by `Component.isMounted() === true` after server-side rendering, while it was always `false` before.

**Closed as completed by RickWong** 2015-11-04 00:47 UTC

**Comment by RickWong** [comment] 2015-11-05 08:02
https://github.com/facebook/react/issues/5383

**Comment by shankie-codes** [comment] 2015-11-06 10:56
Not sure if it's relevant @RickWong , but I'm having the same error message – and I'm not using Transmit.

For me, it appears to be happening if I call a function from an `import` from `componentWillMount` and try to render on the server. The problem goes away if I use `componentDidMount` instead, though obviously that doesn't work on the server.

**Comment by RickWong** [comment] 2015-11-06 11:04
Correction: it's **worked around** in Transmit. The bug is actually inside the React DOM package. See https://github.com/facebook/react/issues/5383 

It's very possible that your project or a dependency in it relies on `isMounted()` on the server, of which the behavior changed since React DOM, and therefore causes identical server-side warnings.

**Comment by shankie-codes** [comment] 2015-11-06 12:01
Thanks for the explanation @RickWong . That makes sense conceptually. I've tried to apply the same workaround to my code with no luck though... any tips? (The BdeAPI calls are pseudo-async calls at the moment that will eventually be replaced by calls to a data store)

```
/* Workaround for https://github.com/RickWong/react-isomorphic-starterkit/issues/77 */
componentDidMount() {
  this._mounted = true;
}

componentWillUnmount() {
  this._mounted = false;
}

_isMounted () {
  // See the official `isMounted` discussion at https://github.com/facebook/react/issues/2787
  return !!this._mounted;
}

componentWillMount() {
  /* Workaround for https://github.com/RickWong/react-isomorphic-starterkit/issues/77 */
  if (!this._isMounted()) {
    BdeApi.getMenuItems(this.handleApiResponse.bind(this,'menuItems'));
    BdeApi.getSubNavItems(this.handleApiResponse.bind(this,'subNavItems'));
    BdeApi.getArtists(this.handleApiResponse.bind(this,'artists'));
    BdeApi.getVenues(this.handleApiResponse.bind(this,'venues'));
    BdeApi.getEditions(this.handleApiResponse.bind(this,'editions'));
    BdeApi.getExhibitors(this.handleApiResponse.bind(this,'exhibitors'));
    BdeApi.getEvents(this.handleApiResponse.bind(this,'events'));
    BdeApi.getPages(this.handleApiResponse.bind(this,'pages'));
  }
}
```

**Comment by RickWong** [comment] 2015-11-06 12:05
Yeah, instead of safe-guarding the async calls like that, you need to safe-guard the actual `setState()` or similar calls with `isMounted()`. I'm guessing that happens in `handleApiResponse`?

**Comment by shankie-codes** [comment] 2015-11-06 12:15
Ah yes, that makes sense, I am doing `setState()` within `handleApiResponse`... but again I still have the same issue. Here's what `handleApiResponse` looks like:

```
handleApiResponse(key, data) {
  if(this._isMounted){
    var dataToSet = {}
    dataToSet[key] = data;
    this.setState(dataToSet);
  }
}
```

Thanks a bunch for your help! I know it's not related to the original issue.

**Comment by RickWong** [comment] 2015-11-06 12:16
You forgot to call `()` the `_isMounted` method ;-)

**Comment by shankie-codes** [comment] 2015-11-06 12:16
I just realised that as soon as I went back to my code!

That's sorted it. Thanks again @RickWong!

**Comment by shankie-codes** [comment] 2015-11-06 12:20
Ah wait, spoke too soon. It's stopped the errors, but it's also stopping `handleApiResponse()` doing it job when it's called in the callback for the async calls – presumably because the component is already mounted when the result comes back from the async call.

**Comment by RickWong** [comment] 2015-11-06 12:22
I'm sorry, can't help. It's becoming very specific to your code.

**Comment by shankie-codes** [comment] 2015-11-06 12:23
No worries, thanks again @RickWong
